### PR TITLE
[Backport] Integration of Vector API (First Incubator)

### PR DESCRIPTION
**Pull request by JoshuaZhuwj**
Summary: Integrate the first incubator of VectorAPI into Dragonwell 11

Test Plan: full jtreg

Reviewed-by: Kuaiwei, Zhuoren

Issue: https://github.com/dragonwell-project/dragonwell11/issues/527

### CODE REVIEW

**Comment by JinZhonghui** [comment]
debug build failed.

src/hotspot/share/opto/idealGraphPrinter.hpp

bool should_print(int level);   was removed by:

8139046: Compiler Control: IGVPrintLevel directive should set PrintIdealGraph
Make !PrintIdealGraph a synonym for PrintIdealGraphLevel=-1 => print nothing

**Review by JinZhonghui — APPROVED** [review]
LGTM

**Comment by JoshuaZhuwj** [comment]
The PR is in the process of verification by full jtreg and performance tests in internal environment.

**Review by sendaoYan — APPROVED** [review]
2023年04月12日测试结果：

image


有三类失败，跟VectorAPI合入没有关系：

1、编译构建问题，appcds相关的用例fail
2、编译构建问题，quickstart相关的用例fail
3、aarch64平台fastdebug有三个http相关的用例超时，应该是aarch64单核性能差的原因

**Comment by JoshuaZhuwj** [comment]
> 2023年04月12日测试结果：
> 
> image
> 
> 有三类失败，跟VectorAPI合入没有关系：
> 
> 1、编译构建问题，appcds相关的用例fail 2、编译构建问题，quickstart相关的用例fail 3、aarch64平台fastdebug有三个http相关的用例超时，应该是aarch64单核性能差的原因

Thanks @sendaoYan for your work on testing and verification.

**Review by kuaiwei — APPROVED** [review]

**Review by sandlerwang — APPROVED** [review]

**Pull request merged**
