### PR TITLE
[Backport] 8333261: riscv: sun/jvm/hotspot/debugger/risv64 should be riscv64

### PR DESCRIPTION
**Pull request by sendaoYan**
Summary: Clean backport of JDK-8333261, this backport has been merged to riscv-port-jdk11u

Testing: CI pipeline

Reviewers: kuaiwei.kw, xingqizheng.xqz

Issue: https://github.com/dragonwell-project/dragonwell11/issues/830

### CODE REVIEW

**Comment by sendaoYan** [comment]
The package name of RISCV64ThreadContext.java is sun.jvm.hotspot.debugger.riscv64, so the directory name of RISCV64ThreadContext.java shoule be `src/jdk.hotspot.agent/share/classes/sun/jvm/hotspot/debugger/riscv64`, rather than `src/jdk.hotspot.agent/share/classes/sun/jvm/hotspot/debugger/risv64`.

**Review by MaxXSoft — APPROVED** [review]
LGTM

**Review by kuaiwei — APPROVED** [review]
LGTM

**Review by kuaiwei — APPROVED** [review]
LGTM

**Pull request merged**
